theme: jekyll-theme-minimal
baseurl: https://stdm2.github.io/stdm2
production_url : https://stdm2.github.io/stdm2
source: documentation/build/html
destination: docs/
include: ["_modules","_sources","_static",_"images"]
timezone: Africa/Nairobi
title: STDM 2.0 Documentation
name: STDM 2.0 Documentation
markdown: 
header: 'STDM 2.0 Documentation'
